# docker-compose.yml

version: '3'

services:
  web:
    image: ulimativ/markdown-blog:latest
    network_mode: "host"
    ports:
      - '80:80'
    restart: unless-stopped
    volumes:
      - ./markdown_files:/app/markdown_files